# Generated by Django 2.1.4 on 2019-01-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190109_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='effect',
            field=models.CharField(choices=[('intelligence', 'intelligence'), ('height', 'height'), ('weight', 'weight'), ('emotional', 'emotional'), ('life_expectancy', 'life_expectancy'), ('none', 'none')], default='none', max_length=20),
        ),
    ]
