# Generated by Django 2.1.4 on 2019-01-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trait_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='effect_val',
            field=models.IntegerField(default=0),
        ),
    ]
